spring:
  application:
    name: Video-Cryptography
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: embedded

video:
  input-file: "input_vid.mp4"
  output-encrypted: "encryptedVideo.mp4"
  decrypted-video: "decryptedVideo.mp4"
  encryptedImageDir: "encrypted_frames/"
  decryptedFrameDir: "decrypted_frames/"


encrypt:
  secret-key: ${SECRET} #Key to generate hash string to encrypt the frames
