spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: Video-Cryptography
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: embedded

video:
  show-encrypted: true
  input-file: "input_vid.mp4"
  output-encrypted: "encryptedVideo.mp4"
  decrypted-video: "decryptedVideo.mp4"


encrypt:
  secret-key: "123456" #random key
