name: Build and Test the application

on:
  workflow_dispatch:
  pull_request:

jobs:
  build-and-test:
    runs-on: windows-latest
    name: Build and test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build and run tests
        shell: bash
        run: |
          mvn clean install --file 'pom.xml' --batch-mode


